apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  DATABASE_HOST: {{ .Values.config.database.host | quote }}
  DATABASE_PORT: {{ .Values.postgres.port | quote }}
  DATABASE_SSLMODE: {{ .Values.config.database.sslmode | quote }}
  SERVER_PORT: {{ .Values.app.port | quote }}
  SERVER_READ_TIMEOUT: {{ .Values.config.server.readTimeout | quote }}
  SERVER_WRITE_TIMEOUT: {{ .Values.config.server.writeTimeout | quote }}
  SERVER_KEEPALIVE_TIMEOUT: {{ .Values.config.server.keepaliveTimeout | quote }}
