apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword }}
  POSTGRES_DB: {{ .Values.secret.postgresDb }}
  DATABASE_USER: {{ .Values.secret.postgresUser }}
  DATABASE_PASSWORD: {{ .Values.secret.postgresPassword }}
  DATABASE_DBNAME: {{ .Values.secret.postgresDb }}