// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/cpbartem2158/CART_API/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddCartItem provides a mock function with given fields: ctx, cartID, product, price
func (_m *MockRepository) AddCartItem(ctx context.Context, cartID int, product string, price float64) (*entity.CartItem, error) {
	ret := _m.Called(ctx, cartID, product, price)

	if len(ret) == 0 {
		panic("no return value specified for AddCartItem")
	}

	var r0 *entity.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, float64) (*entity.CartItem, error)); ok {
		return rf(ctx, cartID, product, price)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, float64) *entity.CartItem); ok {
		r0 = rf(ctx, cartID, product, price)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, float64) error); ok {
		r1 = rf(ctx, cartID, product, price)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_AddCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCartItem'
type MockRepository_AddCartItem_Call struct {
	*mock.Call
}

// AddCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - cartID int
//   - product string
//   - price float64
func (_e *MockRepository_Expecter) AddCartItem(ctx interface{}, cartID interface{}, product interface{}, price interface{}) *MockRepository_AddCartItem_Call {
	return &MockRepository_AddCartItem_Call{Call: _e.mock.On("AddCartItem", ctx, cartID, product, price)}
}

func (_c *MockRepository_AddCartItem_Call) Run(run func(ctx context.Context, cartID int, product string, price float64)) *MockRepository_AddCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *MockRepository_AddCartItem_Call) Return(_a0 *entity.CartItem, _a1 error) *MockRepository_AddCartItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_AddCartItem_Call) RunAndReturn(run func(context.Context, int, string, float64) (*entity.CartItem, error)) *MockRepository_AddCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCart provides a mock function with given fields: ctx
func (_m *MockRepository) CreateCart(ctx context.Context) (*entity.Cart, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateCart")
	}

	var r0 *entity.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entity.Cart, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entity.Cart); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCart'
type MockRepository_CreateCart_Call struct {
	*mock.Call
}

// CreateCart is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) CreateCart(ctx interface{}) *MockRepository_CreateCart_Call {
	return &MockRepository_CreateCart_Call{Call: _e.mock.On("CreateCart", ctx)}
}

func (_c *MockRepository_CreateCart_Call) Run(run func(ctx context.Context)) *MockRepository_CreateCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_CreateCart_Call) Return(_a0 *entity.Cart, _a1 error) *MockRepository_CreateCart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateCart_Call) RunAndReturn(run func(context.Context) (*entity.Cart, error)) *MockRepository_CreateCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function with given fields: ctx, cartID
func (_m *MockRepository) GetCart(ctx context.Context, cartID int) (*entity.Cart, error) {
	ret := _m.Called(ctx, cartID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *entity.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*entity.Cart, error)); ok {
		return rf(ctx, cartID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.Cart); ok {
		r0 = rf(ctx, cartID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, cartID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockRepository_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - cartID int
func (_e *MockRepository_Expecter) GetCart(ctx interface{}, cartID interface{}) *MockRepository_GetCart_Call {
	return &MockRepository_GetCart_Call{Call: _e.mock.On("GetCart", ctx, cartID)}
}

func (_c *MockRepository_GetCart_Call) Run(run func(ctx context.Context, cartID int)) *MockRepository_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetCart_Call) Return(_a0 *entity.Cart, _a1 error) *MockRepository_GetCart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCart_Call) RunAndReturn(run func(context.Context, int) (*entity.Cart, error)) *MockRepository_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCartItem provides a mock function with given fields: ctx, cartID, cartItemID
func (_m *MockRepository) RemoveCartItem(ctx context.Context, cartID int, cartItemID int) error {
	ret := _m.Called(ctx, cartID, cartItemID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, cartID, cartItemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RemoveCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCartItem'
type MockRepository_RemoveCartItem_Call struct {
	*mock.Call
}

// RemoveCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - cartID int
//   - cartItemID int
func (_e *MockRepository_Expecter) RemoveCartItem(ctx interface{}, cartID interface{}, cartItemID interface{}) *MockRepository_RemoveCartItem_Call {
	return &MockRepository_RemoveCartItem_Call{Call: _e.mock.On("RemoveCartItem", ctx, cartID, cartItemID)}
}

func (_c *MockRepository_RemoveCartItem_Call) Run(run func(ctx context.Context, cartID int, cartItemID int)) *MockRepository_RemoveCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_RemoveCartItem_Call) Return(_a0 error) *MockRepository_RemoveCartItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RemoveCartItem_Call) RunAndReturn(run func(context.Context, int, int) error) *MockRepository_RemoveCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
