database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "11111"
  dbname: "database"
  sslmode: "disable"

server:
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"
  keepalive_timeout: "120s"